/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UseStateHookPuttingPropsToUsestateIndexImport } from './routes/use-state-hook/putting-props-to-usestate/index'
import { Route as UseStateHookDontOverUsestateIndexImport } from './routes/use-state-hook/dont-over-usestate/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UseStateHookPuttingPropsToUsestateIndexRoute =
  UseStateHookPuttingPropsToUsestateIndexImport.update({
    path: '/use-state-hook/putting-props-to-usestate/',
    getParentRoute: () => rootRoute,
  } as any)

const UseStateHookDontOverUsestateIndexRoute =
  UseStateHookDontOverUsestateIndexImport.update({
    path: '/use-state-hook/dont-over-usestate/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/use-state-hook/dont-over-usestate/': {
      id: '/use-state-hook/dont-over-usestate/'
      path: '/use-state-hook/dont-over-usestate'
      fullPath: '/use-state-hook/dont-over-usestate'
      preLoaderRoute: typeof UseStateHookDontOverUsestateIndexImport
      parentRoute: typeof rootRoute
    }
    '/use-state-hook/putting-props-to-usestate/': {
      id: '/use-state-hook/putting-props-to-usestate/'
      path: '/use-state-hook/putting-props-to-usestate'
      fullPath: '/use-state-hook/putting-props-to-usestate'
      preLoaderRoute: typeof UseStateHookPuttingPropsToUsestateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UseStateHookDontOverUsestateIndexRoute,
  UseStateHookPuttingPropsToUsestateIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/use-state-hook/dont-over-usestate/",
        "/use-state-hook/putting-props-to-usestate/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/use-state-hook/dont-over-usestate/": {
      "filePath": "use-state-hook/dont-over-usestate/index.tsx"
    },
    "/use-state-hook/putting-props-to-usestate/": {
      "filePath": "use-state-hook/putting-props-to-usestate/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
