/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UseStateHookDontOverUsestateImport } from './routes/use-state-hook/dont-over-usestate'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UseStateHookDontOverUsestateRoute =
  UseStateHookDontOverUsestateImport.update({
    path: '/use-state-hook/dont-over-usestate',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/use-state-hook/dont-over-usestate': {
      id: '/use-state-hook/dont-over-usestate'
      path: '/use-state-hook/dont-over-usestate'
      fullPath: '/use-state-hook/dont-over-usestate'
      preLoaderRoute: typeof UseStateHookDontOverUsestateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UseStateHookDontOverUsestateRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/use-state-hook/dont-over-usestate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/use-state-hook/dont-over-usestate": {
      "filePath": "use-state-hook/dont-over-usestate.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
